### ISSUE TITLE
Error occurred when run "pip install -r requirements.txt" in the terminal

### ISSUE THREAD

**Issue by qiaoyinglin19** [hackerekcah/distinct-events-asc#1]
Hi, Hackerekcah.

Error occurred when run "pip install -r requirements.txt" in the terminal.
Screenshot below.
<img width="1004" alt="屏幕快照 2019-09-03 下午4 48 52" src="https://user-images.githubusercontent.com/49310874/64158357-e5df9080-ce6a-11e9-8f62-523ba75dc186.png">

In addition，there's some question about the format you written in the requirements.txt.
As we know, the first column is the name of the packages while the second column is the version of the packages. What about the third one and the forth one? 

I suppose that the third column seems to be the specific smaller packages of the specific version and the forth one is the name of the packages uploader. Is that right? 

What confused me is that the format of requirements.txt I read in other programs is different from that of this folder. 
For example, 
audioread==2.1.5
backcall==0.1.0

So, why did you write requirements.txt like 
"audioread                 2.1.5                    py36_1000    conda-forge"

I have tried run"pip install -r requirements.txt" under linux system. Unfortunately, same error occurred. 

Would you  mind helping me with those issues above? That would be very nice if you write to me soon.

Best,
Qiaoyinglin

**Comment by hackerekcah** [comment]
Is the problem solved? make sure you create correct virtual environment and the write version of python and pip.

**Comment by qiaoyinglin19** [comment]
Yes, the issue about the requirements had been solved. Thanks a lot for your help.
